"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os
import environ

# DEBUG: Verify DATABASE_URL presence and partial value
db_url = os.environ.get('DATABASE_URL', '')
safe_db_url = db_url[:20] + '...' if db_url else 'NONE'
print(f"DEBUG: os.environ keys: {list(os.environ.keys())}")
print(f"DEBUG: Raw DATABASE_URL check: {safe_db_url}")

# Initialize environment variables
env = environ.Env()
# Read .env file if it exists
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me-in-prod')

DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    'daphne', # Must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'channels',
    'django_q',
    'cloudinary_storage',
    'cloudinary',
    
    # Local apps
    'apps.users',
    'apps.bookings',
    'apps.clinical',
    'apps.community',
    'apps.chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Should be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://postgres:secret@db:5432/vivaclub')
}
DATABASES['default']['CONN_MAX_AGE'] = 600

# DEBUG: Print final DB config (masking password)
if 'default' in DATABASES and 'HOST' in DATABASES['default']:
    print(f"DEBUG: DB Host: {DATABASES['default']['HOST']}")
    print(f"DEBUG: DB Port: {DATABASES['default']['PORT']}")
    print(f"DEBUG: DB Name: {DATABASES['default']['NAME']}")


# Caches & Redis
CACHES = {
    'default': env.cache('REDIS_URL', default='redis://redis:6379/1'),
}

# Channels Layer provided by Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env('REDIS_URL', default='redis://redis:6379/1')],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # For development
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'https://*.railway.app'] # Add frontend domains

# Django-Q Cluster for asynchronous tasks
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'cpu_affinity': 1,
    'save_limit': 250,
    'queue_limit': 500,
    'label': 'Django Q',
    'redis': env('REDIS_URL', default='redis://redis:6379/1')
}

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Cloudinary Storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default='demo'),
    'API_KEY': env('CLOUDINARY_API_KEY', default='demo'),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default='demo'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Firebase FCM
# Firebase FCM
import firebase_admin
from firebase_admin import credentials
import json
import base64

try:
    # 1. Try JSON String from Env (Railway/Cloud)
    firebase_json = env('FIREBASE_CREDENTIALS_JSON', default=None)
    
    if firebase_json:
        # If user copy-pasted raw JSON string
        cred = credentials.Certificate(json.loads(firebase_json))
    else:
        # 2. Try File Path (Local)
        # Check standard GOOGLE_APPLICATION_CREDENTIALS or local file
        default_cred_path = str(BASE_DIR / "vivaclub-c5f16-firebase-adminsdk-fbsvc-259f1e2d17.json")
        cred_path = env('GOOGLE_APPLICATION_CREDENTIALS', default=default_cred_path)
        
        if os.path.exists(cred_path):
            cred = credentials.Certificate(cred_path)
        else:
            cred = None
            print("Warning: Firebase Credentials not found.")

    if cred:
        try:
            firebase_admin.get_app()
        except ValueError:
            firebase_admin.initialize_app(cred)
            print("Firebase Admin Initialized Successfully")
            
except Exception as e:
    print(f"Firebase Init Error: {e}")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
