"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
import os
import environ

# Initialize environment variables
env = environ.Env()
# Read .env file if it exists
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me-in-prod')

DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    'daphne', # Must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'channels',
    'django_q',
    'cloudinary_storage',
    'cloudinary',
    
    # Local apps
    'apps.users',
    'apps.bookings',
    'apps.clinical',
    'apps.community',
    'apps.chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Should be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import dj_database_url
import socket

# Use os.environ.get directly to avoid django-environ issues
db_url = os.environ.get('DATABASE_URL')

if db_url:
    # CRITICAL: Set conn_max_age=0 to close connections after each request
    # This prevents connection pool exhaustion on Railway's Session Mode
    db_config = dj_database_url.parse(db_url, conn_max_age=0)
    
    # Fix for Railway/Supabase IPv6 issues: Force IPv4 resolution
    try:
        hostname = db_config.get('HOST')
        if hostname:
            # Get IPv4 address
            addr_info = socket.getaddrinfo(hostname, None, family=socket.AF_INET)
            if addr_info:
                ip_v4 = addr_info[0][4][0]
                # Pass hostaddr to libpq via OPTIONS to verify SSL correctly but connect via IP
                db_config.setdefault('OPTIONS', {})['hostaddr'] = ip_v4
                print(f"DEBUG: Resolved {hostname} to {ip_v4} (Forcing IPv4)")
    except Exception as e:
        print(f"DEBUG: Failed to resolve IPv4 for DB: {e}")
    
    # Add connection timeout and statement timeout
    db_config.setdefault('OPTIONS', {}).update({
        'connect_timeout': 10,
        'options': '-c statement_timeout=30000'  # 30 second timeout
    })
    
    # Enable atomic requests to auto-close connections
    db_config['ATOMIC_REQUESTS'] = True
        
    DATABASES = {'default': db_config}
else:
    # Fallback for local development if not set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Caches & Redis
import urllib.parse as urlparse_mod
raw_redis_url = os.environ.get('REDIS_URL', 'redis://redis:6379/1')

redis_pass_raw = os.environ.get('REDIS_PASSWORD', 'viva-redis-pass')
redis_pass_encoded = urlparse_mod.quote(redis_pass_raw, safe='')

# Strip any existing credentials from the URL to get host:port/db
parsed = urlparse_mod.urlparse(raw_redis_url)
redis_host = parsed.hostname or 'redis'
redis_port = parsed.port or 6379
redis_db = int(parsed.path.lstrip('/') or '0') if parsed.path and parsed.path != '/' else 0

# Build a clean authenticated URL for Django Cache
redis_url = f'redis://:{redis_pass_encoded}@{redis_host}:{redis_port}/{redis_db}'
os.environ['REDIS_URL'] = redis_url

CACHES = {
    'default': env.cache('REDIS_URL', default=redis_url),
}

# Channels Layer provided by Redis
# Use dict format with string address (NOT tuple!) and raw password separately
# This avoids both the tuple .decode() crash AND URL-encoding issues with special chars
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": f"redis://{redis_host}:{redis_port}/{redis_db}",
                "password": redis_pass_raw,
            }],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'apps.users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Email Settings
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='VivaClub <noreply@vivaclubs.site>')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # For development
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'https://*.railway.app'] # Add frontend domains
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django-Q Cluster for asynchronous tasks
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'cpu_affinity': 1,
    'save_limit': 250,
    'queue_limit': 500,
    'label': 'Django Q',
    'redis': redis_url
}

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Cloudinary Storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default='demo'),
    'API_KEY': env('CLOUDINARY_API_KEY', default='demo'),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default='demo'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Firebase FCM
# Firebase FCM
import firebase_admin
from firebase_admin import credentials
import json
import base64

try:
    # 1. Try JSON String from Env (Railway/Cloud)
    # Check FIREBASE_CREDENTIALS_JSON or GOOGLE_APPLICATION_CREDENTIALS (if it looks like JSON)
    firebase_json = env('FIREBASE_CREDENTIALS_JSON', default=None)
    google_creds = env('GOOGLE_APPLICATION_CREDENTIALS', default=None)
    
    if not firebase_json and google_creds and google_creds.strip().startswith('{'):
        firebase_json = google_creds

    if firebase_json:
        # If user copy-pasted raw JSON string
        cred = credentials.Certificate(json.loads(firebase_json))
    else:
        # 2. Try File Path (Local)
        default_cred_path = str(BASE_DIR / "vivaclub-c5f16-firebase-adminsdk-fbsvc-259f1e2d17.json")
        cred_path = google_creds if google_creds else default_cred_path
        
        if os.path.exists(cred_path):
            cred = credentials.Certificate(cred_path)
        else:
            cred = None
            print("Warning: Firebase Credentials not found.")

    if cred:
        try:
            firebase_admin.get_app()
        except ValueError:
            firebase_admin.initialize_app(cred)
            print("Firebase Admin Initialized Successfully")
            
except Exception as e:
    print(f"Firebase Init Error: {e}")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
