# Generated by Django 5.2.11 on 2026-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('depression', 'Depression Support'), ('anxiety', 'Anxiety Support'), ('relationships', 'Relationships'), ('burnout', 'Burnout'), ('sleep', 'Sleep')], default='general', max_length=50),
        ),
    ]
