# Generated by Django 5.2.11 on 2026-02-11 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_active_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 11, 10, 29, 5, 120837, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
