# Generated by Django 5.2.11 on 2026-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_fcmtoken_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='peak_listeners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='trending_score',
            field=models.FloatField(default=0.0),
        ),
    ]
