# Generated by Django 5.2.11 on 2026-04-24 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_ghostprofile_bio_blockeduser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="banned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="banned_from_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="moderated_rooms", to="community.ghostprofile"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="last_active_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
