# Generated by Django 5.2.13 on 2026-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_room_banned_users_room_moderators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
