# Generated by Django 5.2.11 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_email_verification_token_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_mood",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="last_assessment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_count",
            field=models.IntegerField(default=0),
        ),
    ]
